### ISSUE TITLE
`tx` method on the rpc client fails with InvalidParams error

### ISSUE THREAD

**Issue by jstuczyn** [informalsystems/tendermint-rs#942] opened 2021-08-06 08:37 UTC
Hi! I've been trying to use the rpc client to search for transaction details by its hash (using the `tx` method), unfortunately it's been failing for me with the following error:

```
'called `Result::unwrap()` on an `Err` value: Error { code: InvalidParams, message: "Invalid params", data: Some("error converting json params to arguments: illegal base64 data at input byte 64") }'
```

In my tests I have used `tendermint-rpc 0.21.0` run against `wasmd 0.17` (https://github.com/CosmWasm/wasmd) based validators which under the hood use `cosmos-sdk 0.42.5`.

**Steps to reproduce**

1. Start up a local (or could be remote for all it matters, I've checked it against both live and local instances) validator.

2. Run the following piece of code:
```
    let validator = "http://127.0.0.1:26657";
    let client = HttpClient::new(validator).unwrap();
    let tx_hash = "D716F496764E6D9D24DDCB55841D6E5226261106BFAA4EE31DAC5258DE60B62A"
        .parse()
        .unwrap();
    let res = client.tx(tx_hash, false).await.unwrap();
```

2.1. If you prefer to use the same environment in which it failed for me, the following live validator can also be used:
```
    let validator = "https://testnet-milhon-validator1.nymtech.net";
    let client = HttpClient::new(validator).unwrap();
    let tx_hash = "84A0AD8A48D5CBCC0E551EF29FF96FF9D164699F6C5A53E3B7584A0FC6402E6D"
        .parse()
        .unwrap();
    let res = client.tx(tx_hash, false).await.unwrap();
```

3. It's going to produce the error shown at the beginning of the issue description.

Note: I'm certain the block with the used hash exists as `curl http://127.0.0.1:26657/tx\?hash\=0xD716F496764E6D9D24DDCB55841D6E5226261106BFAA4EE31DAC5258DE60B62A` returns the relevant data. I'm including the response so that perhaps you might be able to spot invalid characters there or something:
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "hash": "D716F496764E6D9D24DDCB55841D6E5226261106BFAA4EE31DAC5258DE60B62A",
    "height": "10802",
    "index": 0,
    "tx_result": {
      "code": 0,
      "data": "CgkKB2V4ZWN1dGU=",
      "log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"execute\"},{\"key\":\"module\",\"value\":\"wasm\"},{\"key\":\"signer\",\"value\":\"punk1q9n5a3cgw3azegcddr82s0f5nxeel4pup8vxzt\"},{\"key\":\"contract_address\",\"value\":\"punk1uft3mmgha04vr23lx08fydpjym2003xuy9cnga\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"punk1uft3mmgha04vr23lx08fydpjym2003xuy9cnga\"},{\"key\":\"sender\",\"value\":\"punk1q9n5a3cgw3azegcddr82s0f5nxeel4pup8vxzt\"},{\"key\":\"amount\",\"value\":\"100000000upunk\"}]},{\"type\":\"wasm\",\"attributes\":[{\"key\":\"contract_address\",\"value\":\"punk1uft3mmgha04vr23lx08fydpjym2003xuy9cnga\"},{\"key\":\"overwritten\",\"value\":\"true\"}]}]}]",
      "info": "",
      "gas_wanted": "200000",
      "gas_used": "136015",
      "events": [
        {
          "type": "transfer",
          "attributes": [
            {
              "key": "cmVjaXBpZW50",
              "value": "cHVuazE3eHBmdmFrbTJhbWc5NjJ5bHM2Zjg0ejNrZWxsOGM1bGg5Y2dkbQ==",
              "index": true
            },
            {
              "key": "c2VuZGVy",
              "value": "cHVuazFxOW41YTNjZ3czYXplZ2NkZHI4MnMwZjVueGVlbDRwdXA4dnh6dA==",
              "index": true
            },
            {
              "key": "YW1vdW50",
              "value": "NTAwMHVwdW5r",
              "index": true
            }
          ]
        },
        {
          "type": "message",
          "attributes": [
            {
              "key": "c2VuZGVy",
              "value": "cHVuazFxOW41YTNjZ3czYXplZ2NkZHI4MnMwZjVueGVlbDRwdXA4dnh6dA==",
              "index": true
            }
          ]
        },
        {
          "type": "message",
          "attributes": [
            {
              "key": "YWN0aW9u",
              "value": "ZXhlY3V0ZQ==",
              "index": true
            }
          ]
        },
        {
          "type": "transfer",
          "attributes": [
            {
              "key": "cmVjaXBpZW50",
              "value": "cHVuazF1ZnQzbW1naGEwNHZyMjNseDA4ZnlkcGp5bTIwMDN4dXk5Y25nYQ==",
              "index": true
            },
            {
              "key": "c2VuZGVy",
              "value": "cHVuazFxOW41YTNjZ3czYXplZ2NkZHI4MnMwZjVueGVlbDRwdXA4dnh6dA==",
              "index": true
            },
            {
              "key": "YW1vdW50",
              "value": "MTAwMDAwMDAwdXB1bms=",
              "index": true
            }
          ]
        },
        {
          "type": "wasm",
          "attributes": [
            {
              "key": "Y29udHJhY3RfYWRkcmVzcw==",
              "value": "cHVuazF1ZnQzbW1naGEwNHZyMjNseDA4ZnlkcGp5bTIwMDN4dXk5Y25nYQ==",
              "index": true
            },
            {
              "key": "b3ZlcndyaXR0ZW4=",
              "value": "dHJ1ZQ==",
              "index": true
            }
          ]
        },
        {
          "type": "message",
          "attributes": [
            {
              "key": "bW9kdWxl",
              "value": "d2FzbQ==",
              "index": true
            },
            {
              "key": "c2lnbmVy",
              "value": "cHVuazFxOW41YTNjZ3czYXplZ2NkZHI4MnMwZjVueGVlbDRwdXA4dnh6dA==",
              "index": true
            },
            {
              "key": "Y29udHJhY3RfYWRkcmVzcw==",
              "value": "cHVuazF1ZnQzbW1naGEwNHZyMjNseDA4ZnlkcGp5bTIwMDN4dXk5Y25nYQ==",
              "index": true
            }
          ]
        }
      ],
      "codespace": ""
    },
    "tx": "Cu8CCtACCikvY29zbXdhc20ud2FzbS52MWJldGExLk1zZ0V4ZWN1dGVDb250cmFjdBKiAgorcHVuazFxOW41YTNjZ3czYXplZ2NkZHI4MnMwZjVueGVlbDRwdXA4dnh6dBIrcHVuazF1ZnQzbW1naGEwNHZyMjNseDA4ZnlkcGp5bTIwMDN4dXk5Y25nYRqxAXsiYm9uZF9taXhub2RlIjp7Im1peF9ub2RlIjp7Imhvc3QiOiIxLjEuMS4xIiwibWl4X3BvcnQiOjE3ODksInZlcmxvY19wb3J0IjoxNzkwLCJodHRwX2FwaV9wb3J0Ijo4MDgwLCJzcGhpbnhfa2V5Ijoic3BoaW54a2V5IiwiaWRlbnRpdHlfa2V5IjoiaWRlbnRpdHlrZXkiLCJ2ZXJzaW9uIjoiMC4xMS4wIn19fSoSCgV1cHVuaxIJMTAwMDAwMDAwEhpCb25kaW5nIG1peG5vZGUgZnJvbSBydXN0IRJnClAKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiED4ko1t6sfd4V/g52JVb3gtj+atBQuVsh7OKZNqJ+HqywSBAoCCAEYIRITCg0KBXVwdW5rEgQ1MDAwEMCaDBpAhVooZoxPyt4KE4lmu17RxqKl7azSTe4CWPLDLy6pRclDsVFCOHfzBoo9Hc2fBIyBBKXRi+T4s8AGZGBF8a8bVQ=="
  }
}
```

Also `tx_search` does work. For context, the code I've used for `tx_search` is as follows:
```
    let validator = "https://testnet-milhon-validator1.nymtech.net";
    let client = HttpClient::new(validator).unwrap();
	let query = Query::from(EventType::Tx).and_eq(
	    "tx.hash",
	    "D716F496764E6D9D24DDCB55841D6E5226261106BFAA4EE31DAC5258DE60B62A",
	);
	let res = client
	    .tx_search(query, false, 1, 20, Order::Ascending)
	    .await
	    .unwrap();
	println!("{:?}", res)
```

**Comment by tony-iqlusion** [comment] 2021-08-06 18:26
I added support for this as part of #863.

I was integration testing against a gaia instance. I just switched `cosmos-sdk-rs` to use this as part of live integration tests against gaia which run in CI in addition to locally, and it's succeeding:

https://github.com/cosmos/cosmos-rust/pull/116

From this error message mentioned above:

> "error converting json params to arguments: illegal base64 data at input byte 64

...it sounds like `wasmd` might want a Base64-encoded transaction hash, rather than a hex one?

It'd be good to confirm that, but if it's true, also annoying that there are two different transaction ID encodings to support.

**Comment by tony-iqlusion** [comment] 2021-08-06 18:45
Edit: sorry about my previous response, I was mistaken.

I managed to reproduce this with gaiad:

```
thread 'msg_send' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid params: error converting json params to arguments: illegal base64 data at input byte 64 (code: -32602)
```

See https://github.com/cosmos/cosmos-rust/pull/116

**Comment by thanethomson** [comment] 2021-08-06 21:05
Also managed to reproduce with Tendermint running the kvstore now. It looks like a difference between how the hash deserialization's handled through the simple HTTP GET interface and the JSON-RPC (POST) interface (we use the JSON-RPC interface from tendermint-rs).

I've tested a base64-encoded transaction hash and it works, but hexadecimal encoding doesn't. The [Tendermint RPC docs for `/tx`](https://docs.tendermint.com/master/rpc/#/Info/tx) seem to be only valid for the HTTP GET interface.

It seems like the HTTP URL client (like when you send GET requests using curl) has its own serialization approach. See [here](https://github.com/tendermint/tendermint/blob/31994cadc0f89d8cd57c23cd5400a6ed039b8acc/rpc/jsonrpc/client/encode.go#L35).

The POST interface, which expects JSON-RPC messages, is dynamically constructed using reflection in Go. See [here](https://github.com/tendermint/tendermint/blob/31994cadc0f89d8cd57c23cd5400a6ed039b8acc/rpc/core/routes.go#L31). This autodetects the method argument types and applies the relevant deserialization strategy to it (which I assume for `[]byte` is base64 en/decoding). There's brief mention of the fix for it over here: https://github.com/tendermint/tendermint/issues/3330#issuecomment-465539103

Will log an issue with the Tendermint team about this to ask about what to do here. Ideally we'd want the format to be consistent, but if we need to cater for base64 encoding here for now then so be it.

**Comment by thanethomson** [comment] 2021-08-06 21:30
https://github.com/tendermint/tendermint/issues/6802 includes information on how to reproduce this locally without our API in the way.

**Comment by thanethomson** [comment] 2021-08-09 21:59
I'm going to implement the base64 encoding here instead of hexadecimal encoding. Will submit a PR soon!

**Comment by thanethomson** [comment] 2021-08-10 13:11
@jstuczyn, with regard to the `/tx_search` endpoint, from integration testing with a Tendermint node running the `kvstore` app, it looks to me like hexadecimal encoding does work. See [here](https://github.com/informalsystems/tendermint-rs/pull/948/files#diff-a5d4b6bc023e90346a617421a613a78054672e23e7a5d49fa394cc3a8fbf6cfdR436). This integration test passes in CI (i.e. it finds the transaction by its corresponding hash). The `Hash::to_string()` method converts to hexadecimal by default.

**Comment by jstuczyn** [comment] 2021-08-10 13:12
Yeah, as I said in my description `/tx_search` **does** work : )

**Comment by thanethomson** [comment] 2021-08-10 13:19
> Yeah, as I said in my description `/tx_search` **does** work : )

Ah sorry! I missed that somehow :grin: Well, now we have an integration test that ensures the serialization format we use for an `abci::transaction::Hash` is supported by Tendermint :slightly_smiling_face: 

Once #948's merged, there are some other changes we need to implement in the next week or so and then we'll aim to cut a new release.

**Closed** 2021-08-18 12:43 UTC
Labels: bug, rpc
